env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
settings:
  react:
    version: 16.0.5
