env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-native
  - prettier
rules:
  indent:
    - error
    - 2
  react-native/no-raw-text:
    - error
  react-native/split-platform-components:
    - error
settings:
  react:
    version: 16.0.5
